vaccines_cget:
    path: ''    # No hay que añadir nada al prefijo
    defaults:
      _controller: AppBundle:Vaccine:vaccines_cget
    methods:
      - GET

users_cget:
    path: ''    # No hay que añadir nada al prefijo
    defaults:
      _controller: AppBundle:Users:users_cget
    methods:
      - GET

vacunauser_cget:
    path: ''    # No hay que añadir nada al prefijo
    defaults:
      _controller: AppBundle:VacunaUser:vacunauser_cget
    methods:
      - GET

vacunaedad_cget:
    path: ''    # No hay que añadir nada al prefijo
    defaults:
      _controller: AppBundle:VacunaEdad:vacunaedad_cget
    methods:
      - GET

vacunaedad_cget_ids:
    path: 'id'    # No hay que añadir nada al prefijo
    defaults:
      _controller: AppBundle:VacunaEdad:vacunaedad_cget_ids
    methods:
      - GET

